spring.application.name=payment-service
spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=elangovan
spring.datasource.password=elangovan

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gateway.url=http://localhost:8080/mock-gateway/pay

callback.url=http://localhost:8080/callbacks/payment

logging.level.root=INFO
logging.level.com.matrix.payment_service=DEBUG
logging.file.name=logs/payment-service.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n